<script lang="ts" setup>
import { type AutoCompleteProps, RuiAutoComplete } from '@rotki/ui-library';
import { objectOmit } from '@vueuse/shared';

interface AutoCompleteData {
  id: string;
  text: string;
  disabled: boolean;
};

const data: AutoCompleteData[] = [
  { id: '1', text: 'Hello 1', disabled: false },
  { id: '2', text: 'Hello 2', disabled: false },
  { id: '3', text: 'Hello 3', disabled: false },
  { id: '4', text: 'Hello 4', disabled: true },
  { id: '5', text: 'Hello 5', disabled: true },
  { id: '6', text: 'Hello 6', disabled: false },
  { id: '7', text: 'Hello 7', disabled: false },
  { id: '8', text: 'Hello 8', disabled: true },
  { id: '9', text: 'Hello 9', disabled: false },
  { id: '10', text: 'Hello 10', disabled: false },
  { id: '11', text: 'Hello 11', disabled: false },
  { id: '12', text: 'Hello 12', disabled: false },
  { id: '13', text: 'Hello 13', disabled: false },
  { id: '14', text: 'Hello 14', disabled: false },
  { id: '15', text: 'Hello 15', disabled: false },
  { id: '16', text: 'Hello 16', disabled: false },
];

const autoCompleteFields = ref<AutoCompleteProps<AutoCompleteData>[]>([
  {
    data,
    modelValue: [
      { id: '4', text: 'Hello 4', disabled: true },
      { id: '5', text: 'Hello 5', disabled: true },
      { id: '6', text: 'Hello 6', disabled: false },
      { id: '7', text: 'Hello 7', disabled: false },
      { id: '8', text: 'Hello 8', disabled: true },
      { id: '9', text: 'Hello 9', disabled: false },
    ],
    placeholder: 'Placeholder',
    color: 'primary',
    variant: 'default',
    label: 'Non Dense',
    nullable: true,
  },
  {
    data,
    modelValue: [
      { id: '4', text: 'Hello 4', disabled: true },
      { id: '5', text: 'Hello 5', disabled: true },
      { id: '6', text: 'Hello 6', disabled: false },
      { id: '7', text: 'Hello 7', disabled: false },
      { id: '8', text: 'Hello 8', disabled: true },
      { id: '9', text: 'Hello 9', disabled: false },
    ],
    placeholder: 'Placeholder',
    color: 'secondary',
    variant: 'default',
    label: 'Non Dense',
    nullable: true,
  },
  {
    data,
    modelValue: [
      { id: '4', text: 'Hello 4', disabled: true },
      { id: '5', text: 'Hello 5', disabled: true },
      { id: '6', text: 'Hello 6', disabled: false },
      { id: '7', text: 'Hello 7', disabled: false },
      { id: '8', text: 'Hello 8', disabled: true },
      { id: '9', text: 'Hello 9', disabled: false },
    ],
    placeholder: 'Placeholder',
    color: 'error',
    variant: 'default',
    label: 'Non Dense',
    nullable: true,
  },
  {
    data,
    modelValue: [
      { id: '4', text: 'Hello 4', disabled: true },
      { id: '5', text: 'Hello 5', disabled: true },
      { id: '6', text: 'Hello 6', disabled: false },
      { id: '7', text: 'Hello 7', disabled: false },
      { id: '8', text: 'Hello 8', disabled: true },
      { id: '9', text: 'Hello 9', disabled: false },
    ],
    placeholder: 'Placeholder',
    color: 'warning',
    variant: 'default',
    label: 'Non Dense',
    nullable: true,
  },
  {
    data,
    modelValue: [
      { id: '4', text: 'Hello 4', disabled: true },
      { id: '5', text: 'Hello 5', disabled: true },
      { id: '6', text: 'Hello 6', disabled: false },
      { id: '7', text: 'Hello 7', disabled: false },
      { id: '8', text: 'Hello 8', disabled: true },
      { id: '9', text: 'Hello 9', disabled: false },
    ],
    placeholder: 'Placeholder',
    color: 'info',
    variant: 'default',
    label: 'API Non Key',
    nullable: true,
  },
  {
    data,
    modelValue: [
      { id: '4', text: 'Hello 4', disabled: true },
      { id: '5', text: 'Hello 5', disabled: true },
      { id: '6', text: 'Hello 6', disabled: false },
      { id: '7', text: 'Hello 7', disabled: false },
      { id: '8', text: 'Hello 8', disabled: true },
      { id: '9', text: 'Hello 9', disabled: false },
    ],
    placeholder: 'Placeholder',
    color: 'success',
    variant: 'default',
    label: 'API Non Secret',
    nullable: true,
  },
  {
    data,
    modelValue: null,
    placeholder: 'Placeholder',
    color: 'primary',
    variant: 'outlined',
    label: 'Non Dense',
    nullable: true,
  },
  {
    data,
    modelValue: null,
    placeholder: 'Placeholder',
    color: 'secondary',
    variant: 'outlined',
    label: 'Non Dense',
    nullable: true,
  },
  {
    data,
    modelValue: null,
    placeholder: 'Placeholder',
    color: 'error',
    variant: 'outlined',
    label: 'Non Dense',
    nullable: true,
  },
  {
    data,
    modelValue: null,
    placeholder: 'Placeholder',
    color: 'warning',
    variant: 'outlined',
    label: 'Non Dense',
    nullable: true,
  },
  {
    data,
    modelValue: null,
    placeholder: 'Placeholder',
    color: 'info',
    variant: 'outlined',
    label: 'API Non Key',
    nullable: true,
  },
  {
    data,
    modelValue: null,
    placeholder: 'Placeholder',
    color: 'success',
    variant: 'outlined',
    label: 'API Non Secret',
    nullable: true,
  },
  {
    data,
    modelValue: [
      { id: '4', text: 'Hello 4', disabled: true },
      { id: '5', text: 'Hello 5', disabled: true },
      { id: '6', text: 'Hello 6', disabled: false },
      { id: '7', text: 'Hello 7', disabled: false },
      { id: '8', text: 'Hello 8', disabled: true },
      { id: '9', text: 'Hello 9', disabled: false },
    ],
    placeholder: 'Placeholder',
    color: 'primary',
    variant: 'filled',
    label: 'Non Dense',
    nullable: true,
  },
  {
    data,
    modelValue: [
      { id: '4', text: 'Hello 4', disabled: true },
      { id: '5', text: 'Hello 5', disabled: true },
      { id: '6', text: 'Hello 6', disabled: false },
      { id: '7', text: 'Hello 7', disabled: false },
      { id: '8', text: 'Hello 8', disabled: true },
      { id: '9', text: 'Hello 9', disabled: false },
    ],
    placeholder: 'Placeholder',
    color: 'secondary',
    variant: 'filled',
    label: 'Non Dense',
    nullable: true,
  },
  {
    data,
    modelValue: [
      { id: '4', text: 'Hello 4', disabled: true },
      { id: '5', text: 'Hello 5', disabled: true },
      { id: '6', text: 'Hello 6', disabled: false },
      { id: '7', text: 'Hello 7', disabled: false },
      { id: '8', text: 'Hello 8', disabled: true },
      { id: '9', text: 'Hello 9', disabled: false },
    ],
    placeholder: 'Placeholder',
    color: 'error',
    variant: 'filled',
    label: 'Non Dense',
    nullable: true,
  },
  {
    data,
    modelValue: [
      { id: '4', text: 'Hello 4', disabled: true },
      { id: '5', text: 'Hello 5', disabled: true },
      { id: '6', text: 'Hello 6', disabled: false },
      { id: '7', text: 'Hello 7', disabled: false },
      { id: '8', text: 'Hello 8', disabled: true },
      { id: '9', text: 'Hello 9', disabled: false },
    ],
    placeholder: 'Placeholder',
    color: 'warning',
    variant: 'filled',
    label: 'Non Dense',
    nullable: true,
  },
  {
    data,
    modelValue: [
      { id: '4', text: 'Hello 4', disabled: true },
      { id: '5', text: 'Hello 5', disabled: true },
      { id: '6', text: 'Hello 6', disabled: false },
      { id: '7', text: 'Hello 7', disabled: false },
      { id: '8', text: 'Hello 8', disabled: true },
      { id: '9', text: 'Hello 9', disabled: false },
    ],
    placeholder: 'Placeholder',
    color: 'info',
    variant: 'filled',
    nullable: true,
  },
  {
    data,
    modelValue: [
      { id: '4', text: 'Hello 4', disabled: true },
      { id: '5', text: 'Hello 5', disabled: true },
      { id: '6', text: 'Hello 6', disabled: false },
      { id: '7', text: 'Hello 7', disabled: false },
      { id: '8', text: 'Hello 8', disabled: true },
      { id: '9', text: 'Hello 9', disabled: false },
    ],
    placeholder: 'Placeholder',
    color: 'success',
    variant: 'filled',
    label: 'API Secret dense',
    nullable: true,
    dense: true,
  },
  {
    data,
    modelValue: null,
    placeholder: 'Placeholder',
    color: 'primary',
    variant: 'default',
    label: 'Dense',
    nullable: true,
    dense: true,
  },
  {
    data,
    modelValue: null,
    placeholder: 'Placeholder',
    color: 'secondary',
    variant: 'default',
    label: 'Dense',
    nullable: true,
    dense: true,
  },
  {
    data,
    modelValue: null,
    placeholder: 'Placeholder',
    color: 'error',
    variant: 'default',
    label: 'Dense',
    nullable: true,
    dense: true,
  },
  {
    data,
    modelValue: null,
    placeholder: 'Placeholder',
    color: 'warning',
    variant: 'default',
    label: 'Dense',
    nullable: true,
    dense: true,
  },
  {
    data,
    modelValue: null,
    placeholder: 'Placeholder',
    color: 'info',
    variant: 'default',
    label: 'API Key',
    nullable: true,
    dense: true,
  },
  {
    data,
    modelValue: null,
    placeholder: 'Placeholder',
    color: 'success',
    variant: 'default',
    label: 'API Secret',
    nullable: true,
    dense: true,
  },
  {
    data,
    modelValue: [
      { id: '4', text: 'Hello 4', disabled: true },
      { id: '5', text: 'Hello 5', disabled: true },
      { id: '6', text: 'Hello 6', disabled: false },
      { id: '7', text: 'Hello 7', disabled: false },
      { id: '8', text: 'Hello 8', disabled: true },
      { id: '9', text: 'Hello 9', disabled: false },
    ],
    placeholder: 'Placeholder',
    color: 'primary',
    variant: 'outlined',
    label: 'Dense',
    nullable: true,
    dense: true,
  },
  {
    data,
    modelValue: [
      { id: '4', text: 'Hello 4', disabled: true },
      { id: '5', text: 'Hello 5', disabled: true },
      { id: '6', text: 'Hello 6', disabled: false },
      { id: '7', text: 'Hello 7', disabled: false },
      { id: '8', text: 'Hello 8', disabled: true },
      { id: '9', text: 'Hello 9', disabled: false },
    ],
    placeholder: 'Placeholder',
    color: 'secondary',
    variant: 'outlined',
    label: 'Dense',
    nullable: true,
    dense: true,
  },
  {
    data,
    modelValue: [
      { id: '4', text: 'Hello 4', disabled: true },
      { id: '5', text: 'Hello 5', disabled: true },
      { id: '6', text: 'Hello 6', disabled: false },
      { id: '7', text: 'Hello 7', disabled: false },
      { id: '8', text: 'Hello 8', disabled: true },
      { id: '9', text: 'Hello 9', disabled: false },
    ],
    placeholder: 'Placeholder',
    color: 'error',
    variant: 'outlined',
    label: 'Dense',
    nullable: true,
    dense: true,
  },
  {
    data,
    modelValue: [
      { id: '4', text: 'Hello 4', disabled: true },
      { id: '5', text: 'Hello 5', disabled: true },
      { id: '6', text: 'Hello 6', disabled: false },
      { id: '7', text: 'Hello 7', disabled: false },
      { id: '8', text: 'Hello 8', disabled: true },
      { id: '9', text: 'Hello 9', disabled: false },
    ],
    placeholder: 'Placeholder',
    color: 'warning',
    variant: 'outlined',
    label: 'Dense',
    nullable: true,
    dense: true,
  },
  {
    data,
    modelValue: [
      { id: '4', text: 'Hello 4', disabled: true },
      { id: '5', text: 'Hello 5', disabled: true },
      { id: '6', text: 'Hello 6', disabled: false },
      { id: '7', text: 'Hello 7', disabled: false },
      { id: '8', text: 'Hello 8', disabled: true },
      { id: '9', text: 'Hello 9', disabled: false },
    ],
    placeholder: 'Placeholder',
    color: 'info',
    variant: 'outlined',
    label: 'API Key',
    nullable: true,
    dense: true,
  },
  {
    data,
    modelValue: [
      { id: '4', text: 'Hello 4', disabled: true },
      { id: '5', text: 'Hello 5', disabled: true },
      { id: '6', text: 'Hello 6', disabled: false },
      { id: '7', text: 'Hello 7', disabled: false },
      { id: '8', text: 'Hello 8', disabled: true },
      { id: '9', text: 'Hello 9', disabled: false },
    ],
    placeholder: 'Placeholder',
    color: 'success',
    variant: 'outlined',
    label: 'API Secret',
    nullable: true,
    dense: true,
  },
  {
    data,
    modelValue: null,
    placeholder: 'Placeholder',
    color: 'primary',
    variant: 'filled',
    label: 'Dense',
    nullable: true,
    dense: true,
  },
  {
    data,
    modelValue: null,
    placeholder: 'Placeholder',
    color: 'secondary',
    variant: 'filled',
    label: 'Dense',
    nullable: true,
    dense: true,
  },
  {
    data,
    modelValue: null,
    placeholder: 'Placeholder',
    color: 'error',
    variant: 'filled',
    label: 'Dense',
    nullable: true,
    dense: true,
  },
  {
    data,
    modelValue: null,
    placeholder: 'Placeholder',
    color: 'warning',
    variant: 'filled',
    label: 'Dense',
    nullable: true,
    dense: true,
  },
  {
    data,
    modelValue: null,
    placeholder: 'Placeholder',
    color: 'info',
    variant: 'filled',
    label: 'API Key dense',
    nullable: true,
    dense: true,
  },
  {
    data,
    modelValue: null,
    placeholder: 'Placeholder',
    color: 'success',
    variant: 'filled',
    label: 'API Secret dense',
    nullable: true,
    dense: true,
  },
]);
</script>

<template>
  <div>
    <h2
      class="text-h4 mb-6"
      data-cy="auto-complete"
    >
      Auto Complete
    </h2>
    <div class="grid gap-6 grid-cols-2">
      <RuiAutoComplete
        v-for="(field, i) in autoCompleteFields"
        :key="i"
        v-model="field.modelValue"
        :data-cy="`auto-complete-${i}`"
        v-bind="objectOmit(field, ['modelValue'])"
      />
    </div>
  </div>
</template>
