<script lang="ts" setup>
import {
  type BadgeProps,
  RuiBadge,
  RuiButton,
} from '@rotki/ui-library/components';
import { ref } from 'vue';

const badges = ref<BadgeProps[]>([
  {
    modelValue: true,
    text: '1',
    color: 'default',
  },
  {
    modelValue: true,
    text: '1',
    color: 'primary',
  },
  {
    modelValue: true,
    text: '1',
    color: 'secondary',
  },
  {
    modelValue: true,
    text: '1',
    color: 'error',
  },
  {
    modelValue: true,
    text: '1',
    color: 'warning',
  },
  {
    modelValue: true,
    text: '1',
    color: 'info',
  },
  {
    modelValue: true,
    text: '1',
    color: 'success',
  },
  {
    modelValue: true,
    text: '1',
    color: 'default',
    placement: 'bottom',
  },
  {
    modelValue: true,
    text: '1',
    color: 'primary',
    placement: 'bottom',
  },
  {
    modelValue: true,
    text: '1',
    color: 'secondary',
    placement: 'bottom',
  },
  {
    modelValue: true,
    text: '1',
    color: 'error',
    placement: 'bottom',
  },
  {
    modelValue: true,
    text: '1',
    color: 'warning',
    placement: 'bottom',
  },
  {
    modelValue: true,
    text: '1',
    color: 'info',
    placement: 'bottom',
  },
  {
    modelValue: true,
    text: '1',
    color: 'success',
    placement: 'bottom',
  },
  {
    modelValue: true,
    text: '1',
    color: 'default',
    left: true,
  },
  {
    modelValue: true,
    text: '1',
    color: 'primary',
    left: true,
  },
  {
    modelValue: true,
    text: '1',
    color: 'secondary',
    left: true,
  },
  {
    modelValue: true,
    text: '1',
    color: 'error',
    left: true,
  },
  {
    modelValue: true,
    text: '1',
    color: 'warning',
    left: true,
  },
  {
    modelValue: true,
    text: '1',
    color: 'info',
    left: true,
  },
  {
    modelValue: true,
    text: '1',
    color: 'success',
    left: true,
  },
  {
    modelValue: true,
    text: '1',
    color: 'default',
    left: true,
    placement: 'bottom',
  },
  {
    modelValue: true,
    text: '1',
    color: 'primary',
    left: true,
    placement: 'bottom',
  },
  {
    modelValue: true,
    text: '1',
    color: 'secondary',
    left: true,
    placement: 'bottom',
  },
  {
    modelValue: true,
    text: '1',
    color: 'error',
    left: true,
    placement: 'bottom',
  },
  {
    modelValue: true,
    text: '1',
    color: 'warning',
    left: true,
    placement: 'bottom',
  },
  {
    modelValue: true,
    text: '1',
    color: 'info',
    left: true,
    placement: 'bottom',
  },
  {
    modelValue: true,
    text: '1',
    color: 'success',
    left: true,
    placement: 'bottom',
  },
  {
    modelValue: true,
    text: '1',
    color: 'default',
    icon: 'star-fill',
  },
  {
    modelValue: true,
    text: '1',
    color: 'primary',
    icon: 'star-fill',
  },
  {
    modelValue: true,
    text: '1',
    color: 'secondary',
    icon: 'star-fill',
  },
  {
    modelValue: true,
    text: '1',
    color: 'error',
    icon: 'star-fill',
  },
  {
    modelValue: true,
    text: '1',
    color: 'warning',
    icon: 'star-fill',
  },
  {
    modelValue: true,
    text: '1',
    color: 'info',
    icon: 'star-fill',
  },
  {
    modelValue: true,
    text: '1',
    color: 'success',
    icon: 'star-fill',
  },
  {
    modelValue: true,
    text: '1',
    color: 'default',
    placement: 'bottom',
    icon: 'star-fill',
  },
  {
    modelValue: true,
    text: '1',
    color: 'primary',
    placement: 'bottom',
    icon: 'star-fill',
  },
  {
    modelValue: true,
    text: '1',
    color: 'secondary',
    placement: 'bottom',
    icon: 'star-fill',
  },
  {
    modelValue: true,
    text: '1',
    color: 'error',
    placement: 'bottom',
    icon: 'star-fill',
  },
  {
    modelValue: true,
    text: '1',
    color: 'warning',
    placement: 'bottom',
    icon: 'star-fill',
  },
  {
    modelValue: true,
    text: '1',
    color: 'info',
    placement: 'bottom',
    icon: 'star-fill',
  },
  {
    modelValue: true,
    text: '1',
    color: 'success',
    placement: 'bottom',
    icon: 'star-fill',
  },
  {
    modelValue: true,
    text: '1',
    color: 'default',
    left: true,
    icon: 'star-fill',
    offsetX: -20,
  },
  {
    modelValue: true,
    text: '1',
    color: 'primary',
    left: true,
    icon: 'star-fill',
    offsetX: -20,
  },
  {
    modelValue: true,
    text: '1',
    color: 'secondary',
    left: true,
    icon: 'star-fill',
    offsetX: -20,
  },
  {
    modelValue: true,
    text: '1',
    color: 'error',
    left: true,
    icon: 'star-fill',
    offsetX: -20,
  },
  {
    modelValue: true,
    text: '1',
    color: 'warning',
    left: true,
    icon: 'star-fill',
    offsetX: -20,
  },
  {
    modelValue: true,
    text: '1',
    color: 'info',
    left: true,
    icon: 'star-fill',
    offsetX: -20,
  },
  {
    modelValue: true,
    text: '1',
    color: 'success',
    left: true,
    icon: 'star-fill',
    offsetX: -20,
  },
  {
    modelValue: true,
    text: '1',
    color: 'default',
    left: true,
    placement: 'bottom',
    icon: 'star-fill',
    offsetX: -20,
  },
  {
    modelValue: true,
    text: '1',
    color: 'primary',
    left: true,
    placement: 'bottom',
    icon: 'star-fill',
    offsetX: -20,
  },
  {
    modelValue: true,
    text: '1',
    color: 'secondary',
    left: true,
    placement: 'bottom',
    icon: 'star-fill',
    offsetX: -20,
  },
  {
    modelValue: true,
    text: '1',
    color: 'error',
    left: true,
    placement: 'bottom',
    icon: 'star-fill',
    offsetX: -20,
  },
  {
    modelValue: true,
    text: '1',
    color: 'warning',
    left: true,
    placement: 'bottom',
    icon: 'star-fill',
    offsetX: -20,
  },
  {
    modelValue: true,
    text: '1',
    color: 'info',
    left: true,
    placement: 'bottom',
    icon: 'star-fill',
    offsetX: -20,
  },
  {
    modelValue: true,
    text: '1',
    color: 'success',
    left: true,
    placement: 'bottom',
    icon: 'star-fill',
    offsetX: -20,
  },
  {
    modelValue: true,
    color: 'default',
    icon: 'star-fill',
  },
  {
    modelValue: true,
    color: 'primary',
    icon: 'star-fill',
  },
  {
    modelValue: true,
    color: 'secondary',
    icon: 'star-fill',
  },
  {
    modelValue: true,
    color: 'error',
    icon: 'star-fill',
  },
  {
    modelValue: true,
    color: 'warning',
    icon: 'star-fill',
  },
  {
    modelValue: true,
    color: 'info',
    icon: 'star-fill',
  },
  {
    modelValue: true,
    color: 'success',
    icon: 'star-fill',
  },
  {
    modelValue: true,
    color: 'default',
    placement: 'bottom',
    icon: 'star-fill',
  },
  {
    modelValue: true,
    color: 'primary',
    placement: 'bottom',
    icon: 'star-fill',
  },
  {
    modelValue: true,
    color: 'secondary',
    placement: 'bottom',
    icon: 'star-fill',
  },
  {
    modelValue: true,
    color: 'error',
    placement: 'bottom',
    icon: 'star-fill',
  },
  {
    modelValue: true,
    color: 'warning',
    placement: 'bottom',
    icon: 'star-fill',
  },
  {
    modelValue: true,
    color: 'info',
    placement: 'bottom',
    icon: 'star-fill',
  },
  {
    modelValue: true,
    color: 'success',
    placement: 'bottom',
    icon: 'star-fill',
  },
  {
    modelValue: true,
    color: 'default',
    left: true,
    icon: 'star-fill',
  },
  {
    modelValue: true,
    color: 'primary',
    left: true,
    icon: 'star-fill',
  },
  {
    modelValue: true,
    color: 'secondary',
    left: true,
    icon: 'star-fill',
  },
  {
    modelValue: true,
    color: 'error',
    left: true,
    icon: 'star-fill',
  },
  {
    modelValue: true,
    color: 'warning',
    left: true,
    icon: 'star-fill',
  },
  {
    modelValue: true,
    color: 'info',
    left: true,
    icon: 'star-fill',
  },
  {
    modelValue: true,
    color: 'success',
    left: true,
    icon: 'star-fill',
  },
  {
    modelValue: true,
    color: 'default',
    left: true,
    placement: 'bottom',
    icon: 'star-fill',
  },
  {
    modelValue: true,
    color: 'primary',
    left: true,
    placement: 'bottom',
    icon: 'star-fill',
  },
  {
    modelValue: true,
    color: 'secondary',
    left: true,
    placement: 'bottom',
    icon: 'star-fill',
  },
  {
    modelValue: true,
    color: 'error',
    left: true,
    placement: 'bottom',
    icon: 'star-fill',
  },
  {
    modelValue: true,
    color: 'warning',
    left: true,
    placement: 'bottom',
    icon: 'star-fill',
  },
  {
    modelValue: true,
    color: 'info',
    left: true,
    placement: 'bottom',
    icon: 'star-fill',
  },
  {
    modelValue: true,
    color: 'success',
    left: true,
    placement: 'bottom',
    icon: 'star-fill',
  },
  {
    modelValue: true,
    text: '1',
    color: 'default',
    dot: true,
  },
  {
    modelValue: true,
    text: '1',
    color: 'primary',
    dot: true,
  },
  {
    modelValue: true,
    text: '1',
    color: 'secondary',
    dot: true,
  },
  {
    modelValue: true,
    text: '1',
    color: 'error',
    dot: true,
  },
  {
    modelValue: true,
    text: '1',
    color: 'warning',
    dot: true,
  },
  {
    modelValue: true,
    text: '1',
    color: 'info',
    dot: true,
  },
  {
    modelValue: true,
    text: '1',
    color: 'success',
    dot: true,
  },
  {
    modelValue: true,
    text: '1',
    color: 'default',
    placement: 'bottom',
    dot: true,
  },
  {
    modelValue: true,
    text: '1',
    color: 'primary',
    placement: 'bottom',
    dot: true,
  },
  {
    modelValue: true,
    text: '1',
    color: 'secondary',
    placement: 'bottom',
    dot: true,
  },
  {
    modelValue: true,
    text: '1',
    color: 'error',
    placement: 'bottom',
    dot: true,
  },
  {
    modelValue: true,
    text: '1',
    color: 'warning',
    placement: 'bottom',
    dot: true,
  },
  {
    modelValue: true,
    text: '1',
    color: 'info',
    placement: 'bottom',
    dot: true,
  },
  {
    modelValue: true,
    text: '1',
    color: 'success',
    placement: 'bottom',
    dot: true,
  },
  {
    modelValue: true,
    text: '1',
    color: 'default',
    left: true,
    dot: true,
  },
  {
    modelValue: true,
    text: '1',
    color: 'primary',
    left: true,
    dot: true,
  },
  {
    modelValue: true,
    text: '1',
    color: 'secondary',
    left: true,
    dot: true,
  },
  {
    modelValue: true,
    text: '1',
    color: 'error',
    left: true,
    dot: true,
  },
  {
    modelValue: true,
    text: '1',
    color: 'warning',
    left: true,
    dot: true,
  },
  {
    modelValue: true,
    text: '1',
    color: 'info',
    left: true,
    dot: true,
  },
  {
    modelValue: true,
    text: '1',
    color: 'success',
    left: true,
    dot: true,
  },
  {
    modelValue: true,
    text: '1',
    color: 'default',
    left: true,
    placement: 'bottom',
    dot: true,
  },
  {
    modelValue: true,
    text: '1',
    color: 'primary',
    left: true,
    placement: 'bottom',
    dot: true,
  },
  {
    modelValue: true,
    text: '1',
    color: 'secondary',
    left: true,
    placement: 'bottom',
    dot: true,
  },
  {
    modelValue: true,
    text: '1',
    color: 'error',
    left: true,
    placement: 'bottom',
    dot: true,
  },
  {
    modelValue: true,
    text: '1',
    color: 'warning',
    left: true,
    placement: 'bottom',
    dot: true,
  },
  {
    modelValue: true,
    text: '1',
    color: 'info',
    left: true,
    placement: 'bottom',
    dot: true,
  },
  {
    modelValue: true,
    text: '1',
    color: 'success',
    left: true,
    placement: 'bottom',
    dot: true,
  },
]);
</script>

<template>
  <div>
    <h2
      class="text-h4 mb-6"
      data-cy="badges"
    >
      Badges
    </h2>
    <div class="grid gap-6 grid-cols-3 lg:grid-cols-7">
      <div
        v-for="(badge, i) in badges"
        :key="i"
        class="p-4"
      >
        <RuiBadge
          v-bind="badge"
          :data-cy="`badge-${i}`"
        >
          <RuiButton @click="badge.modelValue = !badge.modelValue">
            Badge
          </RuiButton>
        </RuiBadge>
      </div>
    </div>
  </div>
</template>
