/* eslint-disable */
/* prettier-ignore */
// oxfmt-ignore
// @ts-nocheck
// noinspection ES6UnusedImports
// Generated by vue-router. !! DO NOT MODIFY THIS FILE !!
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

import type {
  RouteRecordInfo,
  ParamValue,
  ParamValueOneOrMore,
  ParamValueZeroOrMore,
  ParamValueZeroOrOne,
} from 'vue-router'

declare module 'vue-router' {
  interface TypesConfig {
    ParamParsers: never
  }
}

declare module 'vue-router/auto-routes' {
  /**
   * Route name map generated by vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<
      '/',
      '/',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/accordions': RouteRecordInfo<
      '/accordions',
      '/accordions',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/alerts': RouteRecordInfo<
      '/alerts',
      '/alerts',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/auto-completes/': RouteRecordInfo<
      '/auto-completes/',
      '/auto-completes',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/auto-completes/basic': RouteRecordInfo<
      '/auto-completes/basic',
      '/auto-completes/basic',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/auto-completes/custom': RouteRecordInfo<
      '/auto-completes/custom',
      '/auto-completes/custom',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/auto-completes/readonly': RouteRecordInfo<
      '/auto-completes/readonly',
      '/auto-completes/readonly',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/auto-completes/search': RouteRecordInfo<
      '/auto-completes/search',
      '/auto-completes/search',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/auto-completes/selection': RouteRecordInfo<
      '/auto-completes/selection',
      '/auto-completes/selection',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/badges': RouteRecordInfo<
      '/badges',
      '/badges',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/bottom-sheets': RouteRecordInfo<
      '/bottom-sheets',
      '/bottom-sheets',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/breakpoint': RouteRecordInfo<
      '/breakpoint',
      '/breakpoint',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/calendars': RouteRecordInfo<
      '/calendars',
      '/calendars',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/cards': RouteRecordInfo<
      '/cards',
      '/cards',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/checkboxes': RouteRecordInfo<
      '/checkboxes',
      '/checkboxes',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/chips': RouteRecordInfo<
      '/chips',
      '/chips',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/color-pickers': RouteRecordInfo<
      '/color-pickers',
      '/color-pickers',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/data-tables/': RouteRecordInfo<
      '/data-tables/',
      '/data-tables',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/data-tables/basic': RouteRecordInfo<
      '/data-tables/basic',
      '/data-tables/basic',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/data-tables/empty': RouteRecordInfo<
      '/data-tables/empty',
      '/data-tables/empty',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/data-tables/expandable': RouteRecordInfo<
      '/data-tables/expandable',
      '/data-tables/expandable',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/data-tables/grouping': RouteRecordInfo<
      '/data-tables/grouping',
      '/data-tables/grouping',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/data-tables/pagination': RouteRecordInfo<
      '/data-tables/pagination',
      '/data-tables/pagination',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/data-tables/search': RouteRecordInfo<
      '/data-tables/search',
      '/data-tables/search',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/data-tables/selection': RouteRecordInfo<
      '/data-tables/selection',
      '/data-tables/selection',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/data-tables/sorting': RouteRecordInfo<
      '/data-tables/sorting',
      '/data-tables/sorting',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/datetimepickers': RouteRecordInfo<
      '/datetimepickers',
      '/datetimepickers',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/dialogs': RouteRecordInfo<
      '/dialogs',
      '/dialogs',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/dividers': RouteRecordInfo<
      '/dividers',
      '/dividers',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/icons': RouteRecordInfo<
      '/icons',
      '/icons',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/loaders': RouteRecordInfo<
      '/loaders',
      '/loaders',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/logos': RouteRecordInfo<
      '/logos',
      '/logos',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/menu-selects/': RouteRecordInfo<
      '/menu-selects/',
      '/menu-selects',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/menu-selects/basic': RouteRecordInfo<
      '/menu-selects/basic',
      '/menu-selects/basic',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/menu-selects/custom': RouteRecordInfo<
      '/menu-selects/custom',
      '/menu-selects/custom',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/menu-selects/readonly': RouteRecordInfo<
      '/menu-selects/readonly',
      '/menu-selects/readonly',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/menu-selects/selection': RouteRecordInfo<
      '/menu-selects/selection',
      '/menu-selects/selection',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/menus/': RouteRecordInfo<
      '/menus/',
      '/menus',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/navigation-drawers': RouteRecordInfo<
      '/navigation-drawers',
      '/navigation-drawers',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/notification': RouteRecordInfo<
      '/notification',
      '/notification',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/progress': RouteRecordInfo<
      '/progress',
      '/progress',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/radios': RouteRecordInfo<
      '/radios',
      '/radios',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/simple-selects': RouteRecordInfo<
      '/simple-selects',
      '/simple-selects',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/sliders': RouteRecordInfo<
      '/sliders',
      '/sliders',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/steppers': RouteRecordInfo<
      '/steppers',
      '/steppers',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/switches': RouteRecordInfo<
      '/switches',
      '/switches',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/tabs': RouteRecordInfo<
      '/tabs',
      '/tabs',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/text-areas': RouteRecordInfo<
      '/text-areas',
      '/text-areas',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/text-fields': RouteRecordInfo<
      '/text-fields',
      '/text-fields',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/timepickers': RouteRecordInfo<
      '/timepickers',
      '/timepickers',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/tooltips': RouteRecordInfo<
      '/tooltips',
      '/tooltips',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
  }

  /**
   * Route file to route info map by vue-router.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'src/pages/index.vue': {
      routes:
        | '/'
      views:
        | never
    }
    'src/pages/accordions.vue': {
      routes:
        | '/accordions'
      views:
        | never
    }
    'src/pages/alerts.vue': {
      routes:
        | '/alerts'
      views:
        | never
    }
    'src/pages/auto-completes/index.vue': {
      routes:
        | '/auto-completes/'
      views:
        | never
    }
    'src/pages/auto-completes/basic.vue': {
      routes:
        | '/auto-completes/basic'
      views:
        | never
    }
    'src/pages/auto-completes/custom.vue': {
      routes:
        | '/auto-completes/custom'
      views:
        | never
    }
    'src/pages/auto-completes/readonly.vue': {
      routes:
        | '/auto-completes/readonly'
      views:
        | never
    }
    'src/pages/auto-completes/search.vue': {
      routes:
        | '/auto-completes/search'
      views:
        | never
    }
    'src/pages/auto-completes/selection.vue': {
      routes:
        | '/auto-completes/selection'
      views:
        | never
    }
    'src/pages/badges.vue': {
      routes:
        | '/badges'
      views:
        | never
    }
    'src/pages/bottom-sheets.vue': {
      routes:
        | '/bottom-sheets'
      views:
        | never
    }
    'src/pages/breakpoint.vue': {
      routes:
        | '/breakpoint'
      views:
        | never
    }
    'src/pages/calendars.vue': {
      routes:
        | '/calendars'
      views:
        | never
    }
    'src/pages/cards.vue': {
      routes:
        | '/cards'
      views:
        | never
    }
    'src/pages/checkboxes.vue': {
      routes:
        | '/checkboxes'
      views:
        | never
    }
    'src/pages/chips.vue': {
      routes:
        | '/chips'
      views:
        | never
    }
    'src/pages/color-pickers.vue': {
      routes:
        | '/color-pickers'
      views:
        | never
    }
    'src/pages/data-tables/index.vue': {
      routes:
        | '/data-tables/'
      views:
        | never
    }
    'src/pages/data-tables/basic.vue': {
      routes:
        | '/data-tables/basic'
      views:
        | never
    }
    'src/pages/data-tables/empty.vue': {
      routes:
        | '/data-tables/empty'
      views:
        | never
    }
    'src/pages/data-tables/expandable.vue': {
      routes:
        | '/data-tables/expandable'
      views:
        | never
    }
    'src/pages/data-tables/grouping.vue': {
      routes:
        | '/data-tables/grouping'
      views:
        | never
    }
    'src/pages/data-tables/pagination.vue': {
      routes:
        | '/data-tables/pagination'
      views:
        | never
    }
    'src/pages/data-tables/search.vue': {
      routes:
        | '/data-tables/search'
      views:
        | never
    }
    'src/pages/data-tables/selection.vue': {
      routes:
        | '/data-tables/selection'
      views:
        | never
    }
    'src/pages/data-tables/sorting.vue': {
      routes:
        | '/data-tables/sorting'
      views:
        | never
    }
    'src/pages/datetimepickers.vue': {
      routes:
        | '/datetimepickers'
      views:
        | never
    }
    'src/pages/dialogs.vue': {
      routes:
        | '/dialogs'
      views:
        | never
    }
    'src/pages/dividers.vue': {
      routes:
        | '/dividers'
      views:
        | never
    }
    'src/pages/icons.vue': {
      routes:
        | '/icons'
      views:
        | never
    }
    'src/pages/loaders.vue': {
      routes:
        | '/loaders'
      views:
        | never
    }
    'src/pages/logos.vue': {
      routes:
        | '/logos'
      views:
        | never
    }
    'src/pages/menu-selects/index.vue': {
      routes:
        | '/menu-selects/'
      views:
        | never
    }
    'src/pages/menu-selects/basic.vue': {
      routes:
        | '/menu-selects/basic'
      views:
        | never
    }
    'src/pages/menu-selects/custom.vue': {
      routes:
        | '/menu-selects/custom'
      views:
        | never
    }
    'src/pages/menu-selects/readonly.vue': {
      routes:
        | '/menu-selects/readonly'
      views:
        | never
    }
    'src/pages/menu-selects/selection.vue': {
      routes:
        | '/menu-selects/selection'
      views:
        | never
    }
    'src/pages/menus/index.vue': {
      routes:
        | '/menus/'
      views:
        | never
    }
    'src/pages/navigation-drawers.vue': {
      routes:
        | '/navigation-drawers'
      views:
        | never
    }
    'src/pages/notification.vue': {
      routes:
        | '/notification'
      views:
        | never
    }
    'src/pages/progress.vue': {
      routes:
        | '/progress'
      views:
        | never
    }
    'src/pages/radios.vue': {
      routes:
        | '/radios'
      views:
        | never
    }
    'src/pages/simple-selects.vue': {
      routes:
        | '/simple-selects'
      views:
        | never
    }
    'src/pages/sliders.vue': {
      routes:
        | '/sliders'
      views:
        | never
    }
    'src/pages/steppers.vue': {
      routes:
        | '/steppers'
      views:
        | never
    }
    'src/pages/switches.vue': {
      routes:
        | '/switches'
      views:
        | never
    }
    'src/pages/tabs.vue': {
      routes:
        | '/tabs'
      views:
        | never
    }
    'src/pages/text-areas.vue': {
      routes:
        | '/text-areas'
      views:
        | never
    }
    'src/pages/text-fields.vue': {
      routes:
        | '/text-fields'
      views:
        | never
    }
    'src/pages/timepickers.vue': {
      routes:
        | '/timepickers'
      views:
        | never
    }
    'src/pages/tooltips.vue': {
      routes:
        | '/tooltips'
      views:
        | never
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
      ? Info['routes']
      : keyof RouteNamedMap
}

export {}
